Repository TomMelt/mdb, pull requests merged in 2024-01, with the labels that each got.

#9 add type checking to mdb and to the CI workflow
  .github/workflows/code-validation.yml
  CONTRIBUTING.md
  README.md
  mdb/mdb.py
  mdb/mdb_attach.py
  mdb/mdb_client.py
  mdb/mdb_launch.py
  mdb/mdb_shell.py
  mdb/utils.py
  setup.py
Labels: enhancement

#12 fix install of mdb in .readthedocs.yaml
  .readthedocs.yaml
Labels: bug, documentation

#13 Added stdin filter for `interact`
  mdb/mdb_shell.py
Labels: enhancement

#16 update documentation
  README.md
  docs/source/installation.rst
  docs/source/quickstart.rst
  mdb/mdb_shell.py
Labels: documentation

#15 Improve handling of closed debug processes
  mdb/mdb_client.py
  mdb/mdb_shell.py
Labels: enhancement

#19 switch uplot to termgraph
  .github/workflows/tests.yml
  README.md
  docs/source/installation.rst
  docs/source/quick-start.rst
  mdb/mdb_attach.py
  mdb/mdb_shell.py
  setup.py
  tests/test_integration.py
Labels: enhancement

#20 add broadcast mode
  docs/source/quick-start.rst
  mdb/mdb_shell.py
  tests/test_integration.py
Labels: enhancement

#21 improve error handling for typos in command and interact
  mdb/mdb_shell.py
Labels: bug

#22 sort output from do_command
  docs/source/quick-start.rst
  mdb/mdb_shell.py
  tests/test_integration.py
Labels: enhancement
